//CRUD OPERATIONS

export const GET_SHIPMENTS = 'GET_SHIPMENTS';
export const DELETE_SHIPMENT = 'DELETE_SHIPMENT';
export const ADD_SHIPMENT = 'ADD_SHIPMENT';
export const GET_SINGLE_SHIPMENT = 'GET_SINGLE_SHIPMENT';
export const UPDATE_SHIPMENT = 'UPDATE_SHIPMENT';

//OTHERS

export const OPEN_OVERLAY = 'OPEN_OVERLAY';
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY';
